services:
  front:
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:   
      - .env
    ## Uncomment lines below to allow authentication to AWS services
    # volumes:
    #   - ~/.aws/credentials:/home/nextjs/.aws/credentials:ro
    #   - ~/.aws/config:/home/nextjs/.aws/config:ro
    #   - ~/.aws/sso/cache:/home/nextjs/.aws/sso/cache:rw